runtime: nodejs
# runtime: nodejs14
env: flex

service: default

entrypoint: ./docker-entrypoint.sh node ./build/index.js

# instance_class: F2

env_variables:
  DATABASE_URL: "${DATABASE_URL}"
  BROKER: PubSubPush
  APP_ENGINE_URL: "https://test-project-40236.uc.r.appspot.com"
  TEST: ${TEST:-"NOTTEST"}

# inbound_services:
# - warmup

# automatic_scaling:
#   min_instances: 1
