version: '3'

services:
  app:
    build:
      context: .
      target: build
    command: npm run dev
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - "db"


  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: playlists