version: '3'

services:
  app:
    tty: true
    build:
      context: .
      target: build
    command: npm run dev
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - './:/app'
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - "db"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/app/gcloud-auth.json"
      DATABASE_URL: "postgresql://postgres:example@db:5432/playlists?schema=public"
      BROKER: 'Nats'

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: playlists

  nats:
    image: nats
    ports:
      - '4222:4222'