openapi: 3.0.3
info:
  title: Playlist API
  description: Manages playlists for things
  version: 0.1.9

servers:
  - url: http://localhost:8080
    description: Optional server description, e.g. Main (production) server

paths:
  /tracks:
    $ref: "./Tracks/spec/spec.yaml#/~1tracks"

  /playlists:
    $ref: "./Playlists/spec/playlists.yaml#/~1playlists"

  /playlists/{id}:
    $ref: "./Playlists/spec/playlists.yaml#/~1playlists~1{id}"