name: Deploy To Production
 
on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Main Branch Check
        if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
        run: |
          echo "::error Deployment to prod must be from main branch"

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build App (TS)
        run: |
          npm run build

      # - name: Test
      #   run: |
      #     npm run test

      - name: Set up Google Cloud Tools
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: GCP Info
        run: |
          gcloud info

      - name: Deploy To Staging
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TEST: "HOWDY"
        run: |
          ./scripts/prepare-app-deployment.sh staging
          gcloud app deploy app-staging-deployment.yaml --quiet --verbosity info
