name: Merge Master
 
on:
  push:
    branches:
      - main 

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm ci

      - name: Set Version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Tag Version
        run: |
          git tag -a $VERSION -m 'v$VERSION Release'
          git push origin $VERSION

      # - name: Build App (TS)
      #   run: |
      #     npm run build

      # - name: Test
      #   run: |
      #     npm run test

      # - name: Set up Google Cloud Tools
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true

      # - name: GCP Info
      #   run: |
      #     gcloud info

      # - name: Deploy To Staging
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #     TEST: "HOWDY"
      #   run: |
      #     ./scripts/prepare-app-deployment.sh staging
      #     gcloud app deploy app-staging-deployment.yaml --quiet --verbosity info
